### ISSUE TITLE
Paypall

### ISSUE THREAD

**Issue by ACoop** [ACoop/PSWALSB#2]
Also on the "Next Conference" page, please add under the Paypall "$5 charge fee" add:

For No fee Option for you and PSWALSB use Zelle through your bank for direct deposit to PSWALSB's account by entering marsha.cooper@csulb.edu
Takes minutes to set up online on your bank account, and you will get immediate confirmation of transfer.

**Comment by ACoop** [comment]
I think the wording needs work. It seems confusing lets think about another way to say this.

**Comment by Maarsha** [comment]
Fee $5.00
For No fee Option for you and PSWALSB use Zelle via marsha.cooper@csulb.edu with immediate confirmation of transfer.

**Comment by ACoop** [comment]
@Maarsha 
Please preview this change at https://acoop.github.io/PSWALSB

Add label "Ready for Deploy" if you are happy with the change.

**Comment by Maarsha** [comment]
I attached the document here.  The one you have does not have the changes for Zelle
Thanks

**Comment by Maarsha** [comment]
Oops  PayPal is fine. Wrong issue.  I was talking about Word.

**Comment by Maarsha** [comment]
Where is Ready to Deploy  tab

**Comment by ACoop** [comment]
![image](https://user-images.githubusercontent.com/5892617/66878889-d460cc80-ef70-11e9-86b0-057dc8f9acd9.png)

![image](https://user-images.githubusercontent.com/5892617/66878911-f0646e00-ef70-11e9-94ce-7b5e3bdaf61e.png)

**Comment by ACoop** [comment]
Scroll down for "Ready for Deploy"

**Comment by ACoop** [comment]
Actually I removed a few labels to make this easier.

**Comment by Maarsha** [comment]
I attached my screen shot of this page.  The "Label" drops down with no choices.  I have tried to type in the box "Ready to Deploy" but it won't add it as a choice.
I am ready to deploy

**Comment by Maarsha** [comment]
My screen shot is here

**Comment by ACoop** [comment]
@Maarsha it looks like there are comments in the other issue about this one?
