### ISSUE TITLE
Web Master

### ISSUE THREAD

**Issue by ACoop** [ACoop/PSWALSB#3]
on the home page, if you are ready, under Jessica's name add "Webmaster: Andrew Cooper" with link to your email or "Webmaster: coopop@hotmail.com" Your choice.

**Comment by ACoop** [comment]
I will remove for now

**Comment by Maarsha** [comment]
Why?

**Comment by Maarsha** [comment]
You could remove her and put just you

**Comment by ACoop** [comment]
If I want to put this on my resume I would link to this GitHub page
That way a future employer can also see my code and how I manage the page.
