### ISSUE TITLE
Change word document

### ISSUE THREAD

**Issue by Maarsha** [ACoop/PSWALSB#6]
new conference Page Word document

**Comment by Maarsha** [comment]
Payment will be accepted via Zelle, check or by PayPal.

If paying through PayPal, there is a $5 service charge to you and an $8.86 fee to PSWALSB.

 

No Fee Option for both of us: Zelle through your bank for direct deposit to PSWALSB’s account by entering Treasurer’s email: marsha.cooper@csulb.edu

Minutes to set up online on your bank account and it is transferred to PSWALSB with verification sent to you.

 

If paying by check, make check payable to “PSWALSB” and mail to:
Marsha Cooper

PSWALSB

5516 Linda Drive

Torrance, CA 90505

**Comment by ACoop** [comment]
@Maarsha 
Do you have the document?

**Comment by Maarsha** [comment]
I changed it  and added document
Payment will be accepted via Zelle, check or PayPal.
PayPal $5 service charge to you and an $8.86 fee to PSWALSB.
No Fee Option: Zelle on line through your bank for direct deposit to PSWALSB’s account via Treasurer’s email: marsha.cooper@csulb.edu with verification sent to you.
By check: payable to: PSWALSB.  Mail to:
Marsha Cooper, PSWALSB, 5516 Linda Drive Torrance, CA 90505

**Comment by Maarsha** [comment]
The word doc is attached here
